### ISSUE TITLE
The app crashes on iPhone XR 

### ISSUE THREAD

**Issue by erickjth** [EvanBacon/pillar-valley#23]
Hi there. 

After running the app it throws the error described in the screenshot: 

![785370A4-B277-488E-9F65-A57500FAB10D](https://user-images.githubusercontent.com/287978/111892244-ab473580-89c7-11eb-8e9d-3fc6d0071fa7.png)

seems like it is a kind of race condition.

iOS 14.4.1

**Comment by EvanBacon** [comment]
Fixed on latest, sorry for the inconvenience.
