### ISSUE TITLE
installation instructions just don't work

### ISSUE THREAD

**Issue by andylorenz** [EvanBacon/pillar-valley#7]
Its unfortunate but when you are trying to learn a new tool/platform (in my case expo), then the instructions need to be 100% accurate and totally obvious for the newbie ... and this repo is the very first 'recommended' sample project on the expo blog !

So here's what's wrong :

first the installation section starts with "And then create ..."
And ?!  After what ?!
well the first thing to do is surely clone the repo - yes its obvious but it would be nice to just say so?

Ok so I've cloned the repo, so I'm then told to "touch ExpoParty/Secret.js"
really?
but there's no such folder as "ExpoParty"
and why would I want one called that really?
I don't have a clue where this Secret.js file should go to be honest.

"Then go to the Firebase Console and create a Web App." - ok I did that

And finally - "yarn && exp start" ...

Well, actually no. Which folder do I need to navigate to for this to work?  Cos it sure ain't the root !

ok, so I finally worked out that all this stuff should be done in ....
/client/src/

But come on my friend, why can't you spell that out in a few simple, ACCURATE instructions.
As otherwise you are potentially/likely going to put off people like me who want to learn about expo, but will go find something else to try if you just expect newbies to "know their stuff" and work out the easy sh1t for themselves !

**Comment by andylorenz** [comment]
"yarn && exp start" - and yeah, you meant **expo** start didn't you....

**Comment by andylorenz** [comment]
expo start
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class

Metro Bundler process exited with code 1
Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by brentvatne** [comment]
see https://github.com/facebook/react-native/issues/26603

re: exp start -- this project was created a long time ago, before expo-cli existed, and instead exp was used.

**Comment by EvanBacon** [comment]
If you are looking for beginner level projects you should use Expo's free resources https://github.com/expo/examples and not my personal app that was showcased on the Expo blog years ago. 

I hope you don't treat other open source developers like this, as it's extremely demoralizing. Sharing my code for free is not something that I'm required to do, but rather something I do to help others who might find it useful. Your behavior is very disrespectful and I don't condone it on any of my projects.
